### PR TITLE
Update compiler config

### PR DESCRIPTION
**Pull request by tsauerwein**
Update the externs to work with the latest release.

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks for this. Please merge.

**Review by ahocevar — APPROVED** [review]

**Comment by tsauerwein** [comment]
I think this needs some changes for 3.18.2. I will try to take a look in the next days.

**Comment by ahocevar** [comment]
I just tried it, and all I did was set the OpenLayers version in package.json to 3.18.2 and closure-util to 1.15.1. Compiling the app produced warnings, but the app worked fine.

**Comment by tsauerwein** [comment]
Great, I will update this PR.

**Comment by tsauerwein** [comment]
Updated to 3.18.2. Still ok for merging?

**Comment by ahocevar** [comment]
Yes, please. Thanks!

**Comment by tsauerwein** [comment]
Thanks! In fact, I can not merge. I don't have the rights for this repository. Please merge for me. :)

**Comment by fredj** [comment]
@tsauerwein I will add the "ol3" team to this repository

**Comment by tsauerwein** [comment]
Thanks Fred!

**Pull request merged**
